{% set name = "braggedgemodeling" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ornlneutronimaging/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8fc616185642285ce272c914e0d6c71b8f198ba0e2c1ba0fcb73e4c16626b868

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pyyaml
    - numpy
    - scipy
    - matplotlib
    - diffpy.structure
    - periodictable
    
test:
  imports:
    - bem

about:
  home: https://github.com/ornlneutronimaging/braggedgemodeling
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Neutron Bragg Edge Modeling
  doc_url: https://github.com/ornlneutronimaging/braggedgemodeling
  dev_url: https://github.com/ornlneutronimaging/braggedgemodeling

extra:
  recipe-maintainers:
    - yxqd

