travis:
  secure:
    BINSTAR_TOKEN: J+daaFrR8hWUj/0nXyWT28cpCBpJ/dNskrWFG5XVDMZE+Jp7GBEYpXn7heO2ZbMzf9BfQl2VB627MbYRS0rNZJAtVsf2YPEnOa7Hmem55ica6B4YRksZ/ilT3q4MDi50Onb3rcEguMM0fECttDq3JToJ+N9NLVtWaLNk78+EwmAWzjUXxM4zsYc2ci5vQioo1Wz09jefGYujVzFxDuJiFQnU1xkdQObxXp5Cl4HU62A9QGBzpIdL0WG4PYD763MmoJTf2eCUsqjFfEC9+W7UPHM+FxMsLRuwyYY48LuDFvDh2FZhNSrYSoA09pAp8Y1SmD9KTrtU1n09HXeQ8emTXynrl066Kz/UY+pPRNWdaX55qJvDR+4e2ANLpHq2pmhV0DKvEKsdVYosW2MyUoyxcpTW5ykVUVjCp7PWVz5+i1UEoSG84jYxpMap3vuG/Dqg5PtUb2lLHQBg/9VTsdouZ+mx8FFclTGBFX/k4IPfV78xJwXOZsKR+49xcYju4add6EU27/iZiC3h6Vt0i4a57aKPQTQTz3KlspXpLWHuwuIui2meVRb+gkgSi8bsgnsmldHMtwJ19COHCd1hm/J48InwyXmiYRL2rp1z5T1lpLDj7DZ+Se2oO77it7x4E95/ePQsxyh8ycAJeZexRq1rXeC6yp6yvxr9X4YSaYzbKY4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
