travis:
  secure:
    BINSTAR_TOKEN: rjuOvxOlehvkAuLTQ+rptWZOgDYDgynPRj5KSsqMTyrf7KolWNZXPNRPNBBnvRJJRnho5fZh7mfDkcG7zRkROWVVLIHaZGGFdVfeZIwEne7SGHJHvWzNFFfYA34RLcdc1q2XP0a9DYN56BZPhe1nhPcEwDY8zGQR95xQyW+yFlM6KhkfqJHKzCepfAihpaMyJ+BtChhYTN1gwGrsV5/laMTQk74QJ3xVoyTAht4SkFyoHQGRgi4pn3gKtO8rR2E9QE4sS0D/5D7Cmg2wSI7g29ffu8L2zapjC3dZlNd8mY8AKoNgjwsX+oXmwKkJMKEohuM+ZgZxEvCrnnVIiar8fwbcCMTbiDDEykFhZPRmlrNav+taatlu/c890bZuixc5SkWYdEK+dnoc/CRKwHnsbK9SMhl+xolVUDG9pCjTQNMBBalvzQBThHXu3YFHGL4yuPH55z50g7tqWi7Cv5TF/tzwnkfHX7j/dCqvczRaXtL4FScXGytwADF7VO8Ns36pCVuCYkBVG+s0luVKU4biXroMJau+Y/XxdJSG3ZPVB9z9/qCNLuKekS4PTXkIgGh4/GazLkrbgWD17zQbus982z5BTkN3rA+VV9Q9VvL37jEJSOwN35d0fbaM0IBilMTFSoKpKJMH1CgJmqqNGZ5AB4b8bFSgEuB5lk4NW4YRk78=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
